# Generated by Django 4.1.3 on 2022-11-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_store_pickup', models.BooleanField(default=False)),
                ('is_bill_add_equals_deli_add', models.BooleanField(default=False)),
                ('bill_full_name', models.CharField(max_length=50)),
                ('bill_email', models.EmailField(blank=True, max_length=254)),
                ('bill_phone', models.CharField(max_length=100)),
                ('bill_address1', models.CharField(max_length=250)),
                ('bill_address2', models.CharField(max_length=250)),
                ('bill_landmark', models.CharField(blank=True, max_length=255)),
                ('bill_city', models.CharField(max_length=100)),
                ('bill_state', models.CharField(max_length=64)),
                ('bill_pincode', models.CharField(max_length=20)),
                ('deli_full_name', models.CharField(blank=True, max_length=50)),
                ('deli_email', models.EmailField(blank=True, max_length=254)),
                ('deli_phone', models.CharField(blank=True, max_length=100)),
                ('deli_address1', models.CharField(blank=True, max_length=250)),
                ('deli_address2', models.CharField(blank=True, max_length=250)),
                ('deli_landmark', models.CharField(blank=True, max_length=255)),
                ('deli_city', models.CharField(blank=True, max_length=100)),
                ('deli_state', models.CharField(blank=True, max_length=64)),
                ('deli_pincode', models.CharField(blank=True, max_length=20)),
                ('bill_country', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_key', models.CharField(max_length=200)),
                ('payment_option', models.CharField(blank=True, max_length=200)),
                ('billing_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
        ),
    ]
