# Generated by Django 4.1.3 on 2022-11-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill_address1',
            new_name='bill_address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deli_address1',
            new_name='deli_address_line1',
        ),
    ]
