# Generated by Django 4.1.3 on 2022-11-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_bill_address1_order_bill_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill_address2',
            new_name='bill_address_line2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deli_address2',
            new_name='deli_address_line2',
        ),
    ]
