# Generated by Django 4.1.3 on 2022-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_bill_address2_order_bill_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deli_country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_country',
            field=models.CharField(max_length=64),
        ),
    ]
